### ISSUE TITLE
Doge not correct

### ISSUE THREAD

**Issue by HershyReis** [BigNocciolino/CryptoTracker#7]
This is how i have it in a yaml

Bitcoin is a bit off but doge is now at .26 and it shows .19

sensor:
  - platform: cryptostate
    resources:
      - compare: doge-usd
        name: dogecoin

      - compare: btc-usd
        name: bitcoin

      - compare: eth-usd
        name: ethereum

Bitcoin is a bit off but doge is now at .26 and it shows .19

**Comment by BigNocciolino** [comment]
Unfortunately this type of problem does not depend on integration, since each exchange has its own price variations. It is normal that some crypto has a different value from another exchange (ex. Binance).

As for the doge, check the last time the sesnore updated.

And check if there are any errors in the logs.

Check if you have the latest version of the integration, if not, install it. (if you have problems check out this issue to solve: #6 )

If you still have problems do not hesitate to write.

**Comment by HershyReis** [comment]
It’s off by a lot of points. 
It says now .166 when its now at .23 and has not been at .16 in the last week.
There are no errors in the logs that i can see.

Thanks.
